name: tfsec-pr-commenter

on:
  pull_request:
    types: [opened]
  push:
    branches: [main]

jobs:
  tfsec:
    name: tfsec pr commenter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@7a44c5dcde5dfab737363e391800629e27b6376b  # v1.3.1
        with:
          github_token: ${{ github.token }}
